---
services:

  db:
    container_name: pg_tea
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports: [5433:5432]
    volumes: [postgres_data:/var/lib/postgresql/data]
    networks: [teastream-backend]

  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    ports: [16379:6379]
    # command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes: [./redis-conf:/etc/redis]
    networks: [teastream-backend]

  insight:
    image: redis/redisinsight:latest
    container_name: insight
    restart: always
    depends_on: [redis]
    ports: [8002:5540]
    volumes: [redisinsight_data:/data]
    networks: [teastream-backend]
volumes:
  postgres_data:
  # redis_data:
  redisinsight_data:
networks:
  teastream-backend:
